-- Búsqueda dirigida de tablas candidatas a "dirección de planta" y "estatus de pago SAP",
-- excluyendo el ruido de snapshots fechados. Solo nombres de tabla, sin filas.
SELECT table_schema AS dataset, table_name
FROM `proan-quantrue.D00_SANDBOX.INFORMATION_SCHEMA.TABLES`
WHERE REGEXP_CONTAINS(UPPER(table_name), r'BKPF|BSEG|BSAK|BSIK|BSAD|BSID|PAGO|PAYMENT|T001W|ADRC|ADRESS|DIRECCION|PLANTA|WERKS|LFA1|LFB1')

UNION ALL

SELECT table_schema AS dataset, table_name
FROM `proan-quantrue.D20_DIMENSION.INFORMATION_SCHEMA.TABLES`
WHERE REGEXP_CONTAINS(UPPER(table_name), r'BKPF|BSEG|BSAK|BSIK|BSAD|BSID|PAGO|PAYMENT|T001W|ADRC|ADRESS|DIRECCION|PLANTA|WERKS|LFA1|LFB1')

UNION ALL

SELECT table_schema AS dataset, table_name
FROM `proan-quantrue.D30_INTEGRATION.INFORMATION_SCHEMA.TABLES`
WHERE REGEXP_CONTAINS(UPPER(table_name), r'BKPF|BSEG|BSAK|BSIK|BSAD|BSID|PAGO|PAYMENT|T001W|ADRC|ADRESS|DIRECCION|PLANTA|WERKS|LFA1|LFB1')

UNION ALL

SELECT table_schema AS dataset, table_name
FROM `proan-quantrue.D40_EDW.INFORMATION_SCHEMA.TABLES`
WHERE REGEXP_CONTAINS(UPPER(table_name), r'BKPF|BSEG|BSAK|BSIK|BSAD|BSID|PAGO|PAYMENT|T001W|ADRC|ADRESS|DIRECCION|PLANTA|WERKS|LFA1|LFB1')

ORDER BY dataset, table_name;
