SELECT MBLNR, BWART, EBELN, SAFE.PARSE_DATE('%Y%m%d', CAST(BUDAT_MKPF AS STRING)) AS fecha,
  SGTXT, ROUND(DMBTR,2) AS dmbtr, SHKZG, WERKS, KOSTL
FROM `proan-quantrue.D00_SANDBOX.proan_MSEG_HIDROCARBUROS_20260714` mseg
WHERE LIFNR IN (SELECT id_proveedor FROM `proan-quantrue.D20_DIMENSION.dm_vendors` WHERE rfc = 'NQU120510QZ7')
  AND SAKTO = '0005010611'
ORDER BY dmbtr DESC
LIMIT 20;
